; Integer
; Working registers -- rax, rcx, rdx
; Parameter: rdi
; Unused: rbx, rsi, r8-r15
; Linux:
;  - Caller saves: rax, rcx, rdx, rsi, rdi, r8-r11
;  - Callee saves: rbx, rsp, rbp, r12-r15
; Windows:
;  - Caller saves: rax, rcx, rdx, r8-r11, xmm0–xmm5
;  - Callee saves: rbx, rbp, rsi, rdi, r12-r15, xmm6–xmm15

; SSE
; Working registers -- xmm0, xmm1, xmm2
; Unused: xmm3-xmm15 (31)

; AVX
; Working registers -- ymm0, ymm1, ymm2, ymm3
; Unused: ymm4-ymm15 (31)

; AVX-512
; Working registers -- zmm0, zmm1, zmm2, zmm3, k0, k1, k2
; Unused: zmm4-zmm31, k3-k7

; The use of pointers for arrays and structures might be OK. The memory can be made nicely contigous by using a suitable allocator to initialize static structures and arrays.

; -----------------------------------------------------------------------------

%assign true 1
%assign false 0

; -----------------------------------------------------------------------------
; Add
; x = a + b. x, a, b of the same type.

; v0.1

%macro Add.mmu8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  add al, cl
  mov byte [rdi + %1], al
%endmacro

%macro Add.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  add ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Add.mmu32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  add eax, edx
  mov dword [rdi + %1], eax
%endmacro

%macro Add.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  add rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Add.mms8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  add al, cl
  mov byte [rdi + %1], al
%endmacro

%macro Add.mms16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  add ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Add.mms32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  add eax, edx
  mov dword [rdi + %1], eax
%endmacro

%macro Add.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  add rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Add.mmf32 3
  movss xmm0, dword [rdi + %2]
  addss xmm0, dword [rdi + %3]
  movss dword [rdi + %1], xmm0
%endmacro

%macro Add.mmf64 3
  movsd xmm0, qword [rdi + %2]
  addsd xmm0, qword [rdi + %3]
  movsd qword [rdi + %1], xmm0
%endmacro

%macro Add.mmu16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  paddw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Add.mms16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  paddw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Add.miu16 3
  mov ax, word [rdi + %2]
  mov dx, %3
  add ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Add.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  add rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Add.mis64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  add rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Add.rrru64 3
  mov rax, %2
  add rax, %3
  mov %1, rax
%endmacro

%macro Add.miu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpaddb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Add.mmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpaddb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Add.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpaddd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Add.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpaddb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Add.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vaddps xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Add.mmf32x8 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vaddps ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Add.mmf64x8 3
  vmovdqu64 zmm0, zword [rdi + %2]
  vmovdqu64 zmm1, zword [rdi + %3]
  vaddpd zmm0, zmm0, zmm1
  vmovdqu64 zword [rdi + %1], zmm0
%endmacro

%macro Add.mmf32x16 3
  vmovdqu32 zmm0, zword [rdi + %2]
  vmovdqu32 zmm1, zword [rdi + %3]
  vaddps zmm0, zmm0, zmm1
  vmovdqu32 zword [rdi + %1], zmm0
%endmacro

; -----------------------------------------------------------------------------
; Sub
; x = a - b. a, b, c of the same type.

%macro Sub.mmu8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  sub al, cl
  mov byte [rdi + %1], al
%endmacro

%macro Sub.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  sub ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Sub.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  sub rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Sub.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  sub rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Sub.mis64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  sub rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Sub.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  sub rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Sub.imu64 3
  mov rax, %2
  mov rdx, qword [rdi + %3]
  sub rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Sub.rrru64 3
  mov rax, %2
  sub rax, %3
  mov %1, rax
%endmacro

%macro Sub.mmf64 3
  movsd xmm0, [rdi + %2]
  subsd xmm0, [rdi + %3]
  movsd [rdi + %1], xmm0
%endmacro

%macro Sub.mmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpsubb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Sub.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsubd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Sub.rrru8x32 3
  vpsubb %1, %2, %3
%endmacro

%macro Sub.miu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpsubb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Sub.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vsubps xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Sub.mmf32x8 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vsubps ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; Mul
; x = a * b. a, b, c of the same type.

; v0.1

%macro Mul.mmu8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  mul cl
  mov byte [rdi + %1], al
%endmacro

%macro Mul.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  mul dx
  mov word [rdi + %1], ax
%endmacro

%macro Mul.mmu32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  mul edx
  mov dword [rdi + %1], eax
%endmacro

%macro Mul.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mul rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.mms8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  imul dl
  mov byte [rdi + %1], al
%endmacro

%macro Mul.mms16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  imul ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Mul.mms32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  imul eax, edx
  mov dword [rdi + %1], eax
%endmacro

%macro Mul.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  imul rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.mmf32 3
  movd xmm0, dword [rdi + %2]
  movd xmm1, dword [rdi + %3]
  mulss xmm0, xmm1
  movd dword [rdi + %1], xmm0
%endmacro

%macro Mul.mmf64 3
  movsd xmm0, [rdi + %2]
  mulsd xmm0, [rdi + %3]
  movsd [rdi + %1], xmm0
%endmacro

%macro Mul.mms16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmullw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; Polyfill:
; Mul.mmu16x8



; Future

%macro Mul.rrru64 3
  mov rax, %2
  mul %3
  mov %1, rax
%endmacro

%macro Mul.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  mul rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.imu64 3
  mov rax, %2
  mov rdx, qword [rdi + %3]
  mul rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.mis64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  imul rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.ims64 3
  mov rax, %2
  mov rdx, qword [rdi + %3]
  imul rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.iis64 3
  mov rax, %2
  mov rdx, %3
  imul rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Mul.mmu16x16 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpmullw ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Mul.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpmullw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mul.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vmulps xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mul.mmf32x8 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vmulps ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; MulFull -- Multiply two x-bit numbers and store the full 2x-bit result
; x = a op b. a and b of x-bit. x of 2x-bit.

%macro MulFull.mmu8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  mul cl
  mov word [rdi + %1], ax
%endmacro

%macro MulFull.mms64 3
  mov eax, dword [rdi + %2]
  mov ecx, dword [rdi + %3]
  imul ecx
  shl rdx, 32
  or rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro MulFull.mms128 3
  mov rax, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  imul rcx
  mov qword [rdi + %1], rax
  mov qword [rdi + %1 + 8], rdx
%endmacro

%macro MulFull.mmu64x2 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmuludq xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Div
; x = a / b. x, a and b of the same type.

; v0.1

%macro Div.mmu8 3
  mov ax, 0
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  div dl
  mov byte [rdi + %1], al
%endmacro

%macro Div.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, 0
  mov cx, word [rdi + %3]
  div cx
  mov word [rdi + %1], ax
%endmacro

%macro Div.mmu32 3
  mov eax, dword [rdi + %2]
  mov edx, 0
  mov ecx, dword [rdi + %3]
  div ecx
  mov dword [rdi + %1], eax
%endmacro

%macro Div.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, qword [rdi + %3]
  div rcx
  mov qword [rdi + %1], rax
%endmacro

%macro Div.mms8 3
  mov ax, 0
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  idiv dl
  mov byte [rdi + %1], al
%endmacro

%macro Div.mms16 3
  mov ax, word [rdi + %2]
  mov dx, 0
  mov cx, word [rdi + %3]
  idiv cx
  mov word [rdi + %1], ax
%endmacro

%macro Div.mms32 3
  mov eax, dword [rdi + %2]
  mov edx, 0
  mov ecx, dword [rdi + %3]
  idiv ecx
  mov dword [rdi + %1], eax
%endmacro

%macro Div.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, qword [rdi + %3]
  idiv rcx
  mov qword [rdi + %1], rax
%endmacro

%macro Div.mmf32 3
  movss xmm0, [rdi + %2]
  divss xmm0, [rdi + %3]
  movss [rdi + %1], xmm0
%endmacro

%macro Div.mmf64 3
  movsd xmm0, [rdi + %2]
  divsd xmm0, [rdi + %3]
  movsd [rdi + %1], xmm0
%endmacro

; v0.1 polyfill
; Div.mmu16x8



; Future

%macro Div.rrru64 3
  mov rax, %2
  mov rdx, 0
  div %3
  mov %1, rax
%endmacro

%macro Div.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, %3
  div rcx
  mov qword [rdi + %1], rax
%endmacro

%macro Div.rmiu64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, %3
  div rcx
  mov %1, rax
%endmacro

%macro Div.iiu64 3
  mov rax, %2
  mov rdx, 0
  mov rcx, %3
  div rcx
  mov qword [rdi + %1], rax
%endmacro



%macro Div.mis64 3
  mov rax, qword [rdi + %2]
  cqo
  mov rcx, %3
  idiv rcx
  mov qword [rdi + %1], rax
%endmacro

%macro Div.ims64 3
  mov rax, %2
  cqo
  mov rcx, qword [rdi + %3]
  idiv rcx
  mov qword [rdi + %1], rax
%endmacro

%macro Div.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vdivps xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Div.mmf32x8 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vdivps ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; DivFull -- Divide a 2x-bit number by an x-bit number
; x = a op b. a of 2x-bit, b and x of x-bit.

%macro DivFull.mmu8 3
  mov ax, word [rdi + %2]
  mov dl, byte [rdi + %3]
  mov dh, 0
  div dl
  mov byte [rdi + %1], al
%endmacro

; -----------------------------------------------------------------------------
; DivMod
; x, y = a / b. x, y, a, b of the same type.

%macro DivMod.mmu8 4
  mov al, byte [rdi + %3]
  mov ah, 0
  mov cl, byte [rdi + %4]
  div cl
  mov byte [rdi + %1], al
  mov byte [rdi + %2], ah
%endmacro

%macro DivMod.mmu64 4
  mov rax, qword [rdi + %3]
  mov rdx, 0
  mov rcx, qword [rdi + %4]
  div rcx
  mov qword [rdi + %1], rax
  mov qword [rdi + %2], rdx
%endmacro

%macro DivMod.miu64 4
  mov rax, qword [rdi + %3]
  mov rdx, 0
  mov rcx, %4
  div rcx
  mov qword [rdi + %1], rax
  mov qword [rdi + %2], rdx
%endmacro

%macro DivMod.mms64 4
  mov rax, qword [rdi + %3]
  cqo
  mov rcx, qword [rdi + %4]
  idiv rcx
  mov qword [rdi + %1], rax
  mov qword [rdi + %2], rdx
%endmacro

; -----------------------------------------------------------------------------
; Mod
; x = a % b. x, a, b of the same type.

; v0.1

%macro Mod.mmu8 3
  mov ax, 0
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  div dl
  mov byte [rdi + %1], ah
%endmacro

%macro Mod.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, 0
  mov cx, word [rdi + %3]
  div cx
  mov word [rdi + %1], dx
%endmacro

%macro Mod.mmu32 3
  mov eax, dword [rdi + %2]
  mov edx, 0
  mov ecx, dword [rdi + %3]
  div ecx
  mov dword [rdi + %1], edx
%endmacro

%macro Mod.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, qword [rdi + %3]
  div rcx
  mov qword [rdi + %1], rdx
%endmacro

%macro Mod.mms8 3
  mov ax, 0
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  idiv dl
  mov byte [rdi + %1], ah
%endmacro

%macro Mod.mms16 3
  mov ax, word [rdi + %2]
  mov dx, 0
  mov cx, word [rdi + %3]
  idiv cx
  mov word [rdi + %1], dx
%endmacro

%macro Mod.mms32 3
  mov eax, dword [rdi + %2]
  mov edx, 0
  mov ecx, dword [rdi + %3]
  idiv ecx
  mov dword [rdi + %1], edx
%endmacro

%macro Mod.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, 0
  mov rcx, qword [rdi + %3]
  idiv rcx
  mov qword [rdi + %1], rdx
%endmacro

; v0.1 Polyfill
; Mod.mmf32 3
; Mod.mmf64 3
; Mod.mmu16x8


; -----------------------------------------------------------------------------
; MulDiv
; x = a * b / c. x, a, b, c of the same type.

%macro MulDiv.mmu64 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mul rdx
  mov rcx, qword [rdi + %4]
  div rcx
  mov qword [rdi + %1], rax
%endmacro

%macro MulDiv.mms64 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  imul rdx
  mov rcx, qword [rdi + %4]
  idiv rcx
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; AddSaturated -- Addition Saturated
; x = a +| b. x, a, b of the same type.

%macro AddSaturated.mms16 3
  mov rax, 0
  mov ax, word [rdi + %2]
  mov rcx, 0
  mov cx, word [rdi + %3]
  movq xmm0, rax
  movq xmm1, rcx
  paddsw xmm0, xmm1
  movq rax, xmm0
  mov word [rdi + %1], ax
%endmacro

%macro AddSaturated.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpaddusb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; SubSaturated -- Subtraction Saturated
; x = a -| b. x, a, b of the same type.

%macro SubSaturated.mms16 3
  mov rax, 0
  mov ax, word [rdi + %2]
  mov rcx, 0
  mov cx, word [rdi + %3]
  movq xmm0, rax
  movq xmm1, rcx
  psubsw xmm0, xmm1
  movq rax, xmm0
  mov word [rdi + %1], ax
%endmacro

%macro SubSaturated.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsubusb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro SubSaturated.mmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpsubusb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro SubSaturated.mms8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpsubsb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro



; -----------------------------------------------------------------------------
; Round -- Round number to nearest integer
; x = round(a). x, a of the same type.

%macro Round.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  vroundps xmm0, xmm0, 0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Round.mf32x8 2
  vmovdqu ymm0, yword [rdi + %2]
  vroundps ymm0, ymm0, 0
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; Floor -- Round down to nearest integer
; x = floor(a). x, a of the same type.

%macro Floor.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  vroundps xmm0, xmm0, 1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Ceil -- Round up to nearest integer
; x = ceil(a). x, a of the same type.

%macro Ceil.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  vroundps xmm0, xmm0, 2
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Truncate -- Round towards zero
; x = truncate(a). x, a of the same type.

%macro Truncate.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  vroundps xmm0, xmm0, 3
  movdqu oword [rdi + %1], xmm0
%endmacro




; -----------------------------------------------------------------------------
; Abs -- Absolute Value
; x = |a|. x, a of the same type.

; v0.1

%macro Abs.mu8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Abs.mu16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Abs.mu32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Abs.mu64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Abs.ms8 2
  mov al, byte [rdi + %2]
  mov cl, al
  neg al
  cmovl ax, cx
  mov byte [rdi + %2], al
%endmacro

%macro Abs.ms16 2
  mov ax, word [rdi + %2]
  mov cx, ax
  neg ax
  cmovl ax, cx
  mov word [rdi + %2], ax
%endmacro

%macro Abs.ms32 2
  mov eax, dword [rdi + %2]
  mov ecx, eax
  neg eax
  cmovl eax, ecx
  mov dword [rdi + %2], eax
%endmacro

%macro Abs.ms64 2
  mov rax, qword [rdi + %2]
  mov rcx, rax
  neg rax
  cmovl rax, rcx
  mov qword [rdi + %2], rax
%endmacro

%macro Abs.mf32 3
  mov eax, dword [rdi + %2]
	and eax, 0x7FFFFFFF
  mov dword [rdi + %1], eax
%endmacro

%macro Abs.mf64 3
  mov rdx, qword [rdi + %2]
  mov rax, 0x7FFFFFFFFFFFFFFF
	and rdx, rax
  mov qword [rdi + %1], rdx
%endmacro

%macro Abs.mu16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Abs.mu32x4 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Abs.ms16x8 2
  movdqu xmm0, oword [rdi + %2]
  pabsw xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro


; Future

%macro Abs.ms8x16 2
  movdqu xmm0, oword [rdi + %2]
  pabsb xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Abs.ms32x4 2
  movdqu xmm0, oword [rdi + %2]
  pabsd xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Abs.ms64x2 2
  movdqu xmm0, oword [rdi + %2]
  pabsq xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro



; -----------------------------------------------------------------------------
; Mov
; x = a. x, a of the same type.

; v0.1

%macro Mov.iu8 2
  mov al, %2
  mov byte [rdi + %1], al
%endmacro

%macro Mov.iu16 2
  mov ax, %2
  mov word [rdi + %1], ax
%endmacro

%macro Mov.iu32 2
  mov eax, %2
  mov dword [rdi + %1], eax
%endmacro

; The first mov-instruction here is actually a special instruction that can only move to rax.
%macro Mov.iu64 2
  mov rax, %2
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.is8 2
  mov al, %2
  mov byte [rdi + %1], al
%endmacro

%macro Mov.is16 2
  mov ax, %2
  mov word [rdi + %1], ax
%endmacro

%macro Mov.is32 2
  mov eax, %2
  mov dword [rdi + %1], eax
%endmacro

; The first mov-instruction here is actually a special instruction that can only move to rax.
%macro Mov.is64 2
  mov rax, %2
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.mu8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Mov.mu16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Mov.mu32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Mov.mu64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.ms8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Mov.ms16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Mov.ms32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Mov.ms64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.mu16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.ms16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.ib1 2
  mov al, %2
  and al, 1
  mov byte [rdi + %1], al
%endmacro

%macro Mov.ib8 2
  mov al, %2
  mov byte [rdi + %1], al
%endmacro

%macro Mov.ib16 2
  mov ax, %2
  mov word [rdi + %1], ax
%endmacro

%macro Mov.ib32 2
  mov eax, %2
  mov dword [rdi + %1], eax
%endmacro

; The first mov-instruction here is actually a special instruction that can only move to rax.
%macro Mov.ib64 2
  mov rax, %2
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.mb1 2
  mov al, byte [rdi + %2]
  and al, 1
  mov byte [rdi + %1], al
%endmacro

%macro Mov.mb8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Mov.mb16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Mov.mb32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Mov.mb64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.mb16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro



; Future

%macro Mov.riu8 2
  mov %1, %2
%endmacro

%macro Mov.riu16 2
  mov %1, %2
%endmacro

%macro Mov.riu32 2
  mov %1, %2
%endmacro

%macro Mov.ris8 2
  mov %1, %2
%endmacro

%macro Mov.ris16 2
  mov %1, %2
%endmacro

%macro Mov.ris32 2
  mov %1, %2
%endmacro

; Only works with rax, how to warn?
%macro Mov.ris64 2
  mov %1, %2
%endmacro

%macro Mov.rif32 2
  mov %1, __?float32?__(%2)
%endmacro

%macro Mov.rif64 2
  mov %1, __?float64?__(%2)
%endmacro

%macro Mov.mru64 2
  mov qword [rdi + %1], %2
%endmacro

%macro Mov.rmu64 2
  mov %1, qword [rdi + %2]
%endmacro

%macro Mov.iu8x16 2
  mov al, %2
  movzx rax, al
  movq xmm1, rax
  ;vpbroadcastb xmm0, xmm1
  pxor xmm0, xmm0
  vpshufb xmm0, xmm1, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.mu8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.mu32x4 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.iu16x8 2
  mov ax, %2
  movzx rax, ax
  movq xmm1, rax
  ;vpbroadcastw xmm0, xmm1
  pxor xmm0, xmm0
  vpshufw xmm0, xmm1, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.iu32x4 2
  mov rax, %2
  movq xmm1, rax
  ;vpbroadcastd xmm0, xmm1
  vpshufd xmm0, xmm1, 0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.iu64x2 2
  mov rax, %2
  movq xmm1, rax
  vpbroadcastq xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Mov.iu8x32 2
  mov rax, %2
  movq xmm2, rax
  vpbroadcastb ymm0, xmm2
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; TODO: How to deal with Mov vs Broadcast and exp a?
%macro Mov.riu8x32 2
  mov rax, %2
  movq xmm2, rax
  vpbroadcastb %1, xmm2
%endmacro

%macro Mov.if32 2
  mov eax, __?float32?__(%2)
  mov dword [rdi + %1], eax
%endmacro

%macro Mov.if64 2
  mov rax, __?float64?__(%2)
  mov qword [rdi + %1], rax
%endmacro

%macro Mov.mf32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Mov.mf64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Movx8
; x = 1:2:3:4:5:6:7:8

; v0.1

%macro Movx8.iiiiiiiiu16x8 9
  mov rax, %2 | %3 << 16 | %4 << 32 | %5 << 48
  movq xmm0, rax
  mov rax, %6 | %7 << 16 | %8 << 32 | %9 << 48
  pinsrq xmm0, rax, 1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Movx8.iiiiiiiis16x8 9
  mov rax, (%2 & 0xFFFF) | (%3 & 0xFFFF) << 16 | (%4 & 0xFFFF) << 32 | (%5 & 0xFFFF) << 48
  movq xmm0, rax
  mov rax, (%6 & 0xFFFF) | (%7 & 0xFFFF) << 16 | (%8 & 0xFFFF) << 32 | (%9 & 0xFFFF) << 48
  pinsrq xmm0, rax, 1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Movx8.iiiiiiiib16x8 9
  mov rax, %2 | %3 << 16 | %4 << 32 | %5 << 48
  movq xmm0, rax
  mov rax, %6 | %7 << 16 | %8 << 32 | %9 << 48
  pinsrq xmm0, rax, 1
  movdqu oword [rdi + %1], xmm0
%endmacro





; Future

%macro Movx8.iiiiiiiiu32x8 9
  mov rax, %2 | %3 << 32
  movq xmm0, rax
  mov rax, %4 | %5 << 32
  pinsrq xmm0, rax, 1
  mov rax, %6 | %7 << 32
  movq xmm1, rax
  mov rax, %8 | %9 << 32
  pinsrq xmm1, rax, 1
  vinserti128 ymm0, ymm0, xmm1, 1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; Broadcast
; x = (AtoB)a.

%macro Broadcast.mu16x8 2
  vpbroadcastw xmm0, word [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Broadcast.ms16x8 2
  vpbroadcastw xmm0, word [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Broadcast.mu16x16 2
  vpbroadcastw ymm0, word [rdi + %2]
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Broadcast.mu16x32 2
  vpbroadcastw zmm0, word [rdi + %2]
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

; -----------------------------------------------------------------------------
; Loop
; No parameters

%macro Loop 1
  %1:
%endmacro

; -----------------------------------------------------------------------------
; Len
; x = len(a). x must be a number. a must be an array.

%macro Len 2
  mov rax, qword [rdi + %2]
  mov rax, qword [rax - 8]
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Lt
; x = a < b. x is a boolean. a and b are of the same type.

; v0.1

%macro Lt.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpltss xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Lt.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmpltsd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Lt.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pcmpgtw xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

; Polyfill
; Lt.mmb16x8u16x8



; Future

%macro Lt.rrrb1u64 3
  cmp %2, %3
  setb %1
%endmacro

%macro Lt.iib1u16 3
  mov ax, %2
  mov dx, %3
  cmp ax, dx
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.iib1u64 3
  mov rax, %2
  mov rdx, %3
  cmp rax, rdx
  setb al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.iib1s16 3
  mov ax, %2
  mov dx, %3
  cmp ax, dx
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mib8x32u8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpcmpgtb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Lt.mmb8x32s8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpgtb xmm0, xmm1, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Lt.mib1f64 3
  movsd xmm0, [rdi + %2]
  mov rax, __?float64?__(%3)
  movq xmm1, rax
  cmpltsd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Lt.mib1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  cmp rax, rdx
  setl al
  mov byte [rdi + %1], al
%endmacro

%macro Lt.mmb32x4f32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vcmpltps xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Lte
; x = a <= b. x is a boolean. a and b are of the same type.

; v0.1

%macro Lte.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setbe al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setbe al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setbe al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setbe al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setle al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setle al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setle al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setle al
  mov byte [rdi + %1], al
%endmacro

%macro Lte.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpless xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Lte.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmplesd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Lte.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  movdqu xmm2, xmm1
  pcmpgtw xmm1, xmm0
  pcmpeqw xmm2, xmm0
  por xmm1, xmm2
  movdqu oword [rdi + %1], xmm1
%endmacro

; Polyfill
; Lte.mmb16x8u16x8



; Future

%macro Lte.mmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpcmpgtb ymm2, ymm0, ymm1
  vpcmpeqb ymm3, ymm3, ymm3
  vpxor ymm0, ymm2, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Lte.rrru8x32 3
  vpcmpgtb ymm2, %2, %3
  vpcmpeqb ymm3, ymm3, ymm3
  vpxor %1, ymm2, ymm3
%endmacro

%macro Lte.miu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpcmpgtb ymm2, ymm0, ymm1
  vpcmpeqb ymm3, ymm3, ymm3
  vpxor ymm0, ymm2, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Lte.mms8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpgtb xmm0, xmm0, xmm1
  vpcmpeqb xmm1, xmm1, xmm1 ; zero
  vpxor xmm0, xmm0, xmm1    ; not
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Gt
; x = a > b. x is a boolean. a and b are of the same type.

; v0.1

%macro Gt.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  seta al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  seta al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  seta al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  seta al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setg al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setg al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setg al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setg al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpgtss xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Gt.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmpgtsd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Gt.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pcmpgtw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; Polyfill
; Gt.mmb16x8u16x8




; Future

%macro Gt.mib1u8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpcmpgtb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Gt.mmb1u8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpcmpgtb ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Gt.mib1f64 3
  movsd xmm0, [rdi + %2]
  mov rax, __?float64?__(%3)
  movq xmm1, rax
  cmpnlesd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Gt.mib1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  cmp rax, rdx
  setg al
  mov byte [rdi + %1], al
%endmacro

%macro Gt.mmb8x16u8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpgtb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Gt.mmb8x16s8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpgtb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Gte
; x = a >= b. x is a boolean. a and b are of the same type.

; v0.1

%macro Gte.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setae al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setae al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setae al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setae al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setge al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setge al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setge al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setge al
  mov byte [rdi + %1], al
%endmacro

%macro Gte.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpgess xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Gte.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmpgesd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Gte.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm2, xmm0
  movdqu xmm1, oword [rdi + %3]
  pcmpgtw xmm0, xmm1
  pcmpeqw xmm2, xmm1
  por xmm0, xmm2
  movdqu oword [rdi + %1], xmm0
%endmacro

; Polyfill
; Gte.mmb16x8u16x8



; Future

%macro Gte.mmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpcmpgtb ymm2, ymm0, ymm1
  vpcmpeqb ymm3, ymm0, ymm1
  vpor ymm0, ymm2, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Gte.rmmu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpcmpgtb ymm2, ymm0, ymm1
  vpcmpeqb ymm3, ymm0, ymm1
  vpor %1, ymm2, ymm3
%endmacro

%macro Gte.rrru8x32 3
  vpcmpgtb ymm2, %2, %3
  vpcmpeqb ymm3, %2, %3
  vpor %1, ymm2, ymm3
%endmacro

%macro Gte.miu8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpcmpgtb ymm2, ymm0, ymm1
  vpcmpeqb ymm3, ymm0, ymm1
  vpor ymm0, ymm2, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Gte.mms8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpgtb xmm0, xmm1, xmm0
  vpcmpeqd xmm1, xmm1, xmm1 ; zero
  vpxor xmm0, xmm0, xmm1    ; not
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Not
; x = !a. x and a are booleans.

; v0.1

%macro Not.mb1 2
  mov al, byte [rdi + %2]
  not al
  and al, 1
  mov byte [rdi + %1], al 
%endmacro

%macro Not.mb8 2
  mov al, byte [rdi + %2]
  not al
  mov byte [rdi + %1], al 
%endmacro

%macro Not.mb16 2
  mov ax, word [rdi + %2]
  not ax
  mov word [rdi + %1], ax
%endmacro

%macro Not.mb32 2
  mov eax, dword [rdi + %2]
  not eax
  mov dword [rdi + %1], eax
%endmacro

%macro Not.mm32 2
  kmovd k1, dword [rdi + %2]
  knotd k1, k1
  kmovd dword [rdi + %1], k1
%endmacro

%macro Not.mb64 2
  mov rax, qword [rdi + %2]
  not rax
  mov qword [rdi + %1], rax
%endmacro

%macro Not.mb16x8 2
  movdqu xmm0, oword [rdi + %2]
  pcmpeqb xmm1, xmm1
  pxor xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro



; Future

%macro Not.mu8x32 2
  vmovdqu ymm0, yword [rdi + %2]
  vpcmpeqb ymm3, ymm3, ymm3
  vpxor ymm0, ymm0, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Not.mb256 2
  vmovdqu ymm0, yword [rdi + %2]
  vpcmpeqb ymm3, ymm3, ymm3
  vpxor ymm0, ymm0, ymm3
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Not.mb128 2
  movdqu xmm0, oword [rdi + %2]
  pcmpeqb xmm3, xmm3
  pxor xmm0, xmm3
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; And
; x = a & b. x, a, b are booleans.

; v0.1

%macro And.mmb1 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  and al, cl
  and al, 1
  mov byte [rdi + %1], al
%endmacro

%macro And.mmb8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  and al, cl
  and al, 1
  mov byte [rdi + %1], al
%endmacro

%macro And.mmb16 3
  mov ax, word [rdi + %2]
  mov cx, word [rdi + %3]
  and ax, cx
  mov word [rdi + %1], ax
%endmacro

%macro And.mmb32 3
  mov eax, dword [rdi + %2]
  mov ecx, dword [rdi + %3]
  and eax, ecx
  mov dword [rdi + %1], eax
%endmacro

%macro And.mmm32 3
  kmovd k1, dword [rdi + %2]
  kmovd k2, dword [rdi + %3]
  kandd k1, k1, k2
  kmovd dword [rdi + %1], k1
%endmacro

%macro And.mmb64 3
  mov rax, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  and rax, rcx
  mov qword [rdi + %1], rax
%endmacro

%macro And.mmb16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpand xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro And.mmb8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpand xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro And.mmb32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpand xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro And.mmb8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpand ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro


%macro And.mmb128 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpand xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro And.mmb16x16 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpand ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro And.mmb16x32 3
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu16 zmm1, zword [rdi + %3]
  vpandq zmm0, zmm0, zmm1
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

%macro And.rrrb8x32 3
  vpand %1, %2, %3
%endmacro

%macro And.mib8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  mov rax, %3
  movq xmm2, rax
  vpbroadcastb ymm1, xmm2
  vpand ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; Andnot
; x = !a & b. x, a, b are booleans.

%macro Andnot.mmb64 3
  mov rax, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  andn rdx, rax, rcx
  mov qword [rdi + %1], rdx
%endmacro

%macro Andnot.mmb128 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpandn xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; If
; If a. a is a boolean.

; v0.1

%macro If.mb1 2
  test byte [rdi + %1], 1
  jz %2
%endmacro

%macro If.mb8 2
  mov al, 0xFF
  mov cl, byte [rdi + %1]
  cmp al, cl
  jne %2
%endmacro



; Future

%macro If.rb1 2
  mov al, 0
  mov cl, %1
  and cl, 1
  cmp al, cl
  je %2
%endmacro

%macro If.mu8 2
  mov al, 0
  mov cl, byte [rdi + %1]
  cmp al, cl
  je %2
%endmacro

; -----------------------------------------------------------------------------
; Endloop
; No parameters

%macro EndLoop 2
  jmp %1
  %2:
%endmacro

; -----------------------------------------------------------------------------
; Endb
; No parameters

%macro Endb 1
  %1:
%endmacro

; -----------------------------------------------------------------------------
; Idr
; x = a[b]. b must be a number. a must be an array. x must be of the same type as the array's elements.

; v0.1

%macro Idr.mmu8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.mmu16a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mmu32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mmu64a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mms8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.mms16a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mms32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mms64a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mmb8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.mmb16a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mmb32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mmb64a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mmf32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mmf64a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mmu16x8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.mms16x8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.mmb16x8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.miu8a 3
  mov rax, qword [rdi + %2]
  mov al, byte [rax + %3 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.miu16a 3
  mov rax, qword [rdi + %2]
  mov ax, word [rax + %3 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.miu32a 3
  mov rax, qword [rdi + %2]
  mov eax, dword [rax + %3 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.miu64a 3
  mov rax, qword [rdi + %2]
  mov rax, qword [rax + %3 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mis8a 3
  mov rax, qword [rdi + %2]
  mov al, byte [rax + %3 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.mis16a 3
  mov rax, qword [rdi + %2]
  mov ax, word [rax + %3 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mis32a 3
  mov rax, qword [rdi + %2]
  mov eax, dword [rax + %3 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mis64a 3
  mov rax, qword [rdi + %2]
  mov rax, qword [rax + %3 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mib8a 3
  mov rax, qword [rdi + %2]
  mov al, byte [rax + %3 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idr.mib16a 3
  mov rax, qword [rdi + %2]
  mov ax, word [rax + %3 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mib32a 3
  mov rax, qword [rdi + %2]
  mov eax, dword [rax + %3 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mib64a 3
  mov rax, qword [rdi + %2]
  mov rax, qword [rax + %3 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.mif32a 3
  mov rax, qword [rdi + %2]
  mov eax, dword [rax + %3 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mif64a 3
  mov rax, qword [rdi + %2]
  mov rax, qword [rax + %3 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.miu16x8a 3
  mov rax, qword [rdi + %2]
  movdqu xmm0, oword [rax + %3 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.mis16x8a 3
  mov rax, qword [rdi + %2]
  movdqu xmm0, oword [rax + %3 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.mib16x8a 3
  mov rax, qword [rdi + %2]
  movdqu xmm0, oword [rax + %3 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.miu16x8 3
  movdqu xmm0, oword [rdi + %2]
  vpextrw rax, xmm0, %3
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mis16x8 3
  movdqu xmm0, oword [rdi + %2]
  vpextrw rax, xmm0, %3
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mib16x8 3
  movdqu xmm0, oword [rdi + %2]
  vpextrw rax, xmm0, %3
  mov word [rdi + %1], ax
%endmacro

%macro Idr.mmsta 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro


; Future

%macro Idr.rrru64a 3
  mov %1, qword [%2 + %3 * 8]
%endmacro

%macro Idr.mmu8x32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 5
  vmovdqu ymm0, yword [rax + rdx]
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Idr.mmu16x16a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 5
  vmovdqu ymm0, yword [rax + rdx]
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Idr.mmu16x32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 6
  vmovdqu16 zmm0, zword [rax + rdx]
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

%macro Idr.rmmu8x32a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 5
  vmovdqu %1, yword [rax + rdx]
%endmacro

%macro Idr.rmru8x32a 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  shl rdx, 5
  vmovdqu %1, yword [rax + rdx]
%endmacro

%macro Idr.rrru8x32a 3
  mov rdx, %3
  shl rdx, 5
  vmovdqu %1, yword [%2 + rdx]
%endmacro

%macro Idr.mista 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  mov rax, qword [rax + rdx * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idr.miu8x16 3
  movdqu xmm0, oword [rdi + %2]
  vpextrb al, xmm0, %3
  mov byte [rdi + %1], al
%endmacro

%macro Idr.miu32x4 3
  movdqu xmm0, oword [rdi + %2]
  vpextrd eax, xmm0, %3
  mov dword [rdi + %1], eax
%endmacro

%macro Idr.mmu8x16a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idr.miu8x16a 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx]
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Idro -- Index Read Array with offset
; x = a[b + c]. b and c must be numbers. a must be an array. x must be of the same type as the array's elements.

; v0.1

%macro Idro.mmiu8a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1 + %4 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idro.mmiu16a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2 + %4 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idro.mmiu32a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4 + %4 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idro.mmiu64a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8 + %4 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idro.mmis8a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1 + %4 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idro.mmis16a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2 + %4 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idro.mmis32a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4 + %4 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idro.mmis64a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8 + %4 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idro.mmib8a 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov al, byte [rax + rdx * 1 + %4 * 1]
  mov byte [rdi + %1], al
%endmacro

%macro Idro.mmib16a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov ax, word [rax + rdx * 2 + %4 * 2]
  mov word [rdi + %1], ax
%endmacro

%macro Idro.mmib32a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4 + %4 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idro.mmib64a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8 + %4 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idro.mmif32a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov eax, dword [rax + rdx * 4 + %4 * 4]
  mov dword [rdi + %1], eax
%endmacro

%macro Idro.mmif64a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  mov rax, qword [rax + rdx * 8 + %4 * 8]
  mov qword [rdi + %1], rax
%endmacro

%macro Idro.mmiu16x8a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx + %4 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idro.mmis16x8a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx + %4 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idro.mmib16x8a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx + %4 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro








; Future

%macro Idro.mmiu16x16a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 5
  vmovdqu ymm0, yword [rax + rdx + %4 * 32]
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Idro.mmiu16x32a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 6
  vmovdqu16 zmm0, zword [rax + rdx + %4 * 64]
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

%macro Idro.mmiu8x16a 4
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  shl rdx, 4
  movdqu xmm0, oword [rax + rdx + %4 * 16]
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Eq -- Equal
; x = a = b. x is a boolean. a and b are the same types.

; v0.1

%macro Eq.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpeqss xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Eq.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmpeqsd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Eq.mmb16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpeqw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Eq.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpeqw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Eq.mmb1b1 3
  mov al, byte [rdi + %2]
  and al, 1
  mov dl, byte [rdi + %3]
  and dl, 1
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1b8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1b16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1b32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb1b64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmb16x8b16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpeqw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Eq.mmu8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.miu8 3
  mov al, byte [rdi + %2]
  mov dl, %3
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.miu16 3
  mov ax, word [rdi + %2]
  mov dx, %3
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmu32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.miu32 3
  mov eax, dword [rdi + %2]
  mov edx, %3
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mms64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.iiu16 3
  mov ax, %2
  mov dx, %3
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mib1 3
  mov al, byte [rdi + %2]
  mov dl, %3
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mis8 3
  mov al, byte [rdi + %2]
  mov dl, %3
  cmp al, dl
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mis16 3
  mov ax, word [rdi + %2]
  mov dx, %3
  cmp ax, dx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mis32 3
  mov eax, dword [rdi + %2]
  mov edx, %3
  cmp eax, edx
  sete al
  mov byte [rdi + %1], al
%endmacro

%macro Eq.mis64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  cmp rax, rdx
  sete al
  mov byte [rdi + %1], al
%endmacro

; Could have used comiss
%macro Eq.mif32 3
  movss xmm0, [rdi + %2]
  mov eax, __?float32?__(%3)
  movd xmm1, eax
  cmpeqss xmm0, xmm1
  movd eax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Eq.mif64 3
  movsd xmm0, [rdi + %2]
  mov rax, __?float64?__(%3)
  movq xmm1, rax
  cmpeqsd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Eq.mmu16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pcmpeqb xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Eq.mmb16x16u16x16 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpcmpeqw ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Eq.mmb16x32u16x32 3
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu16 zmm1, zword [rdi + %3]
  vpcmpeqw k1, zmm0, zmm1
  vpmovm2w zmm0, k1
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

%macro Eq.mmm32u16x32 3
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu16 zmm1, zword [rdi + %3]
  vpcmpeqw k1, zmm0, zmm1
  kmovd dword [rdi + %1], k1
%endmacro

%macro Eq.mmb32u16x32 3
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu16 zmm1, zword [rdi + %3]
  vpcmpeqw k1, zmm0, zmm1
  kmovd dword [rdi + %1], k1
%endmacro

%macro Eq.mms8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpeqb xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Eq.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vcmpeqps xmm0, xmm1, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Neq -- Not equal
; x = a != b. x is a boolean. a and b are the same types.

; v0.1

%macro Neq.mmb1u8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1u16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1u32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1u64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1s8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1s16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1s32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1s64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1f32 3
  movss xmm0, [rdi + %2]
  movss xmm1, [rdi + %3]
  cmpness xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Neq.mmb1f64 3
  movsd xmm0, [rdi + %2]
  movsd xmm1, [rdi + %3]
  cmpnesd xmm0, xmm1
  movq rax, xmm0
  cmp al, 255
  sete [rdi + %1]
%endmacro

%macro Neq.mmb16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pcmpeqw xmm0, xmm1
  pcmpeqd xmm2, xmm2 ; This is a
  pxor xmm0, xmm2    ; not instruction
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Neq.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pcmpeqw xmm0, xmm1
  pcmpeqd xmm2, xmm2 ; This is a
  pxor xmm0, xmm2    ; not instruction
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Neq.mmb1b8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1b16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1b32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb1b64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setne al
  mov byte [rdi + %1], al
%endmacro




; Future

%macro Neq.mmu16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmu64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.miu64 3
  mov rax, qword [rdi + %2]
  mov rdx, %3
  cmp rax, rdx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.miu32 3
  mov eax, dword [rdi + %2]
  mov edx, %3
  cmp eax, edx
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mib1 3
  mov al, byte [rdi + %2]
  mov dl, %3
  cmp al, dl
  setne al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb256 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpxor ymm2, ymm0, ymm1
  vptest ymm2, ymm2
  setnz al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mmb512 3
  vmovdqu64 zmm0, zword [rdi + %2]
  vmovdqu64 zmm1, zword [rdi + %3]
  vpxorq zmm2, zmm0, zmm1
  vptest zmm2, zmm2
  setnz al
  mov byte [rdi + %1], al
%endmacro

%macro Neq.mms8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpcmpeqb xmm0, xmm0, xmm1
  vpcmpeqb xmm1, xmm1, xmm1 ; zero
  vpxor xmm0, xmm0, xmm1    ; not
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Acw -- Structure write element
; x.y = a. x must be a structure type. a and y must be of the same types.

%macro Acw.mmu16 3
  mov ax, word [rdi + %3]
  mov rdx, qword [rdi + %1]
  mov word [rdx + %2], ax
%endmacro

%macro Acw.mmu64 3
  mov rax, qword [rdi + %3]
  mov rdx, qword [rdi + %1]
  mov qword [rdx + %2], rax
%endmacro

%macro Acw.mms64 3
  mov rax, qword [rdi + %3]
  mov rdx, qword [rdi + %1]
  mov qword [rdx + %2], rax
%endmacro

%macro Acw.miu64 3
  mov rax, %3
  mov rdx, qword [rdi + %1]
  mov qword [rdx + %2], rax
%endmacro

; -----------------------------------------------------------------------------
; Acr -- Structure read element
; x = a.b. a must be a structure type. x and b must be of the same types.

%macro Acr.mmu64 3
  mov rax, [rdi + %2]
  mov rax, [rax + %3]
  mov [rdi + %1], rax
%endmacro

%macro Acr.mms64 3
  mov rax, [rdi + %2]
  mov rax, [rax + %3]
  mov [rdi + %1], rax
%endmacro

%macro Acr.mmb1 3
  mov rax, [rdi + %2]
  mov al, byte [rax + %3]
  mov [rdi + %1], al
%endmacro

%macro Acr.mmf64 3
  mov rax, [rdi + %2]
  mov rax, [rax + %3]
  mov [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Inc -- Increment by 1
; x++. x must be a number type.

; v0.1

%macro Inc.mu8 1
  inc byte [rdi + %1]
%endmacro

%macro Inc.mu16 1
  inc word [rdi + %1]
%endmacro

%macro Inc.mu32 1
  inc dword [rdi + %1]
%endmacro

%macro Inc.mu64 1
  inc qword [rdi + %1]
%endmacro

%macro Inc.ms8 1
  inc byte [rdi + %1]
%endmacro

%macro Inc.ms16 1
  inc word [rdi + %1]
%endmacro

%macro Inc.ms32 1
  inc dword [rdi + %1]
%endmacro

%macro Inc.ms64 1
  inc qword [rdi + %1]
%endmacro

%macro Inc.mf32 1
  movss xmm0, dword [rdi + %1]
  mov eax, 1
  cvtsi2ss xmm1, eax
  addss xmm0, xmm1
  movss dword [rdi + %1], xmm0
%endmacro

%macro Inc.mf64 1
  movsd xmm0, qword [rdi + %1]
  mov eax, 1
  cvtsi2sd xmm1, eax
  addsd xmm0, xmm1
  movsd qword [rdi + %1], xmm0
%endmacro

; Polyfill
; Inc.mu16x8
; Inc.ms16x8


; Future

%macro Inc.ru64 1
  inc %1
%endmacro

; -----------------------------------------------------------------------------
; Dec - Decrement by 1
; x--. x must be a number type.

; v0.1

%macro Dec.mu8 1
  dec byte [rdi + %1]
%endmacro

%macro Dec.mu16 1
  dec word [rdi + %1]
%endmacro

%macro Dec.mu32 1
  dec dword [rdi + %1]
%endmacro

%macro Dec.mu64 1
  dec qword [rdi + %1]
%endmacro

%macro Dec.ms8 1
  dec byte [rdi + %1]
%endmacro

%macro Dec.ms16 1
  dec word [rdi + %1]
%endmacro

%macro Dec.ms32 1
  dec dword [rdi + %1]
%endmacro

%macro Dec.ms64 1
  dec qword [rdi + %1]
%endmacro

%macro Dec.mf32 1
  movss xmm0, dword [rdi + %1]
  mov eax, 1
  cvtsi2ss xmm1, eax
  subss xmm0, xmm1
  movss dword [rdi + %1], xmm0
%endmacro

%macro Dec.mf64 1
  movsd xmm0, qword [rdi + %1]
  mov eax, 1
  cvtsi2sd xmm1, eax
  subsd xmm0, xmm1
  movsd qword [rdi + %1], xmm0
%endmacro

; Polyfill
; Dec.mu16x8
; Dec.ms16x8


; Future





%macro Dec.ru64 1
  dec %1
%endmacro

; -----------------------------------------------------------------------------
; Shl -- Shift left
; x = a << b. x and a must be bit fields. b must be a number type

; v0.1

%macro Shl.mmb8u8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  shl eax, cl
  mov byte [rdi + %1], al
%endmacro

%macro Shl.mmb16u8 3
  mov ax, word [rdi + %2]
  mov cl, byte [rdi + %3]
  shl ax, cl
  mov word [rdi + %1], ax
%endmacro

%macro Shl.mmb32u8 3
  mov eax, dword [rdi + %2]
  mov cl, byte [rdi + %3]
  shl eax, cl
  mov dword [rdi + %1], eax
%endmacro

%macro Shl.mmb64u8 3
  mov rax, qword [rdi + %2]
  mov cl, byte [rdi + %3]
  shl rax, cl
  mov qword [rdi + %1], rax
%endmacro

%macro Shl.mmu16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsllvw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Shl.miu32u64 3
  mov eax, dword [rdi + %2]
  shl eax, %3
  mov dword [rdi + %1], eax
%endmacro

%macro Shl.mib128u64 3
  movdqu xmm0, oword [rdi + %2]
  pslldq xmm0, %3
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Shl.miu32x4u64 3
  movdqu xmm0, oword [rdi + %2]
  mov rax, %3
  movq xmm1, rax
  vpbroadcastd xmm1, xmm1
  vpsllvd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Shl.mmu32x4u32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsllvd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Shr - Shift right
; x = a >> b. x and a must be bit fields. b must be a number type

; v0.1

%macro Shr.mmb8u8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  shr eax, cl
  mov byte [rdi + %1], al
%endmacro

%macro Shr.mmb16u8 3
  mov ax, word [rdi + %2]
  mov cl, byte [rdi + %3]
  shr ax, cl
  mov word [rdi + %1], ax
%endmacro

%macro Shr.mmb32u8 3
  mov eax, dword [rdi + %2]
  mov cl, byte [rdi + %3]
  shr eax, cl
  mov dword [rdi + %1], eax
%endmacro

%macro Shr.mmb64u8 3
  mov rax, qword [rdi + %2]
  mov cl, byte [rdi + %3]
  shr rax, cl
  mov qword [rdi + %1], rax
%endmacro

%macro Shr.mmu16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsrlvw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Shr.miu32 3
  mov eax, dword [rdi + %2]
  shr eax, %3
  mov dword [rdi + %1], eax
%endmacro

%macro Shr.miu64 3
  mov rax, qword [rdi + %2]
  shr rax, %3
  mov qword [rdi + %1], rax
%endmacro

%macro Shr.mib128 3
  movdqu xmm0, oword [rdi + %2]
  psrldq xmm0, %3
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Shr.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsrlvd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Sar - Shift arithmetic right
; x = a op b. x and a must be bit fields. b must be a number type

%macro Shr.mis32 3
  mov eax, dword [rdi + %2]
  sar eax, %3
  mov dword [rdi + %1], eax
%endmacro

%macro Sar.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpsravd xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Or
; x = a | b. x, a, b must be the same bitfield types.

; v0.1

%macro Or.mmb1 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  or al, cl
  and al, 1
  mov byte [rdi + %1], al
%endmacro

%macro Or.mmb8 3
  mov al, byte [rdi + %2]
  mov cl, byte [rdi + %3]
  or al, cl
  mov byte [rdi + %1], al
%endmacro

%macro Or.mmb16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  or ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Or.mmb32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  or eax, edx
  mov dword [rdi + %1], eax
%endmacro

%macro Or.mmb64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  or rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Or.mmb16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Or.mmm32 3
  kmovd k1, dword [rdi + %2]
  kmovd k2, dword [rdi + %3]
  kord k1, k1, k2
  kmovd dword [rdi + %1], k1
%endmacro

%macro Or.mmb8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpor ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Or.mmb16x16 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpor ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Or.mmb8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Or.mmb16x32 3
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu16 zmm1, zword [rdi + %3]
  vporq zmm0, zmm0, zmm1
  vmovdqu16 zword [rdi + %1], zmm0
%endmacro

%macro Or.mmb32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Or.mmb128 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Xor
; x = a ^ b. x, a, b must be the same bitfield types.

; v0.1

%macro Xor.mmb8 3
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  xor al, dl
  mov byte [rdi + %1], al
%endmacro

%macro Xor.mmb16 3
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  xor ax, dx
  mov word [rdi + %1], ax
%endmacro

%macro Xor.mmb32 3
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  xor eax, edx
  mov dword [rdi + %1], eax
%endmacro

%macro Xor.mmb64 3
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  xor rax, rdx
  mov qword [rdi + %1], rax
%endmacro

%macro Xor.mmb16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pxor xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro







; Future

%macro Xor.mmb8x32 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpxor ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Xor.mmb8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpxor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xor.mmb32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpxor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xor.mmb128 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpxor xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Call
; f(x). x must be a structure.

%macro Call 2
  push rdi
  mov rdi, [rdi + %2]
  call %1
  pop rdi
%endmacro

; -----------------------------------------------------------------------------
; Else
; No parameters

%macro Else 2
  jmp %2
  %1:
%endmacro

; -----------------------------------------------------------------------------
; New
; x = New(S). The type of x must be S.

extern malloc

%macro New 2
  push rdi
  push rdi
  mov rdi, %2_size
  call malloc
  pop rdi
  pop rdi
  mov [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Del
; Del(x).

extern free

%macro Del.mstr 1
  push rdi
  push rdi
  mov rdi, [rdi + %1]
  call free
  pop rdi
  pop rdi
%endmacro

; -----------------------------------------------------------------------------
; Idw
; x = a[b]. b must be a number type. a must be array. x must be the same as a's element types.

; v0.1

%macro Idw.mmu8a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.mmu16a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.mmu32a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.mmu64a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.mms8a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.mms16a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.mms32a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.mms64a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.mmb8a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.mmb16a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.mmb32a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.mmb64a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.mmf32a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.mmf64a 3
  mov rcx, qword [rdi + %2]
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.mmu16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.mms16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.mmb16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.imu8a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.imu16a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.imu32a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.imu64a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.ims8a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.ims16a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.ims32a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.ims64a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.imb8a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 1]
  mov cl, byte [rdi + %3]
  mov byte [rax], cl
%endmacro

%macro Idw.imb16a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 2]
  mov cx, word [rdi + %3]
  mov word [rax], cx
%endmacro

%macro Idw.imb32a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.imb64a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.imf32a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 4]
  mov ecx, dword [rdi + %3]
  mov dword [rax], ecx
%endmacro

%macro Idw.imf64a 3
  mov rax, [rdi + %1]
  lea rax, [rax + %2 * 8]
  mov rcx, qword [rdi + %3]
  mov qword [rax], rcx
%endmacro

%macro Idw.imu16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  movdqu oword [rax + %2 * 16], xmm0
%endmacro

%macro Idw.ims16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  movdqu oword [rax + %2 * 16], xmm0
%endmacro

%macro Idw.imb16x8a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  movdqu oword [rax + %2 * 16], xmm0
%endmacro

%macro Idw.imu16x8 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, 0
  mov ax, word [rdi + %3]
  vpinsrw xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.ims16x8 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, 0
  mov ax, word [rdi + %3]
  vpinsrw xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.imb16x8 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, 0
  mov ax, word [rdi + %3]
  vpinsrw xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro





; Future

%macro Idw.iiu16a 3
  mov rcx, %2
  mov rax, [rdi + %1]
  lea rax, [rax + rcx * 2]
  mov cx, %3
  mov word [rax], cx
%endmacro

%macro Idw.mmu8x32a 3
  vmovdqu ymm0, yword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 5
  vmovdqu yword [rax + rcx], ymm0
%endmacro

%macro Idw.mmu8x16a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.mmu32x4a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.imu32x4a 3
  movdqu xmm0, oword [rdi + %3]
  mov rax, qword [rdi + %1]
  mov rcx, %2
  shl rcx, 4
  movdqu oword [rax + rcx], xmm0
%endmacro

%macro Idw.mru8x32a 3
  mov rax, qword [rdi + %1]
  mov rcx, qword [rdi + %2]
  shl rcx, 5
  vmovdqu yword [rax + rcx], %3
%endmacro

%macro Idw.mrru8x32a 3
  mov rax, qword [rdi + %1]
  mov rcx, %2
  shl rcx, 5
  vmovdqu yword [rax + rcx], %3
%endmacro

%macro Idw.rrru8x32a 3
  mov rcx, %2
  shl rcx, 5
  vmovdqu yword [%1 + rcx], %3
%endmacro

%macro Idw.iiu8x16 3
  movdqu xmm0, oword [rdi + %1]
  mov al, %3
  vpinsrb xmm0, al, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iis8x16 3
  movdqu xmm0, oword [rdi + %1]
  mov al, %3
  vpinsrb xmm0, al, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.miu8x16 3
  movdqu xmm0, oword [rdi + %1]
  mov al, byte [rdi + %3]
  vpinsrb xmm0, al, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iiu16x8 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, %3
  vpinsrw xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iis16x8 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, %3
  vpinsrw xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iis32x4 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, %3
  vpinsrd xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.imu32x4 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, dword [rdi + %3]
  vpinsrd xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iiu32x4 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, %3
  vpinsrd xmm0, eax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.imf32x4 3
  movdqu xmm0, oword [rdi + %1]
  movd xmm1, dword [rdi + %3]
  insertps xmm0, xmm1, %2 << 4
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.imf64x8 3
  vmovdqu64 zmm0, zword [rdi + %1]
  vmovq xmm1, qword [rdi + %3]
  mov eax, 1 << %2
  kmovw k1, eax
  vbroadcastsd zmm0 {k1}, xmm1
  vmovdqu64 zword [rdi + %1], zmm0
%endmacro

%macro Idw.iif32x4 3
  movdqu xmm0, oword [rdi + %1]
  mov eax, __?float32?__(%3)
  movq xmm1, rax
  insertps xmm0, xmm1, %2 << 4
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iif64x2 3
  movdqu xmm0, oword [rdi + %1]
  mov rax, __?float64?__(%3)
  vpinsrq xmm0, rax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Idw.iiu32x8 3
  vmovdqu ymm0, yword [rdi + %1]
  vextracti128 xmm1, ymm0, %3 / 8
  mov eax, %3
  vpinsrd xmm1, eax, %2 % 8
  vinserti128 ymm0, xmm1, %3 / 8
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Idw.iiu64x2 3
  movdqu xmm0, oword [rdi + %1]
  mov rax, %3
  vpinsrq xmm0, rax, %2
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Rdrand
; x = Rdrand(). x must be a number type

%macro Rdrand.mu64 2
  rdrand rax
  mov qword [rdi + %1], rax
  setc byte [rdi + %2]
%endmacro

; -----------------------------------------------------------------------------
; Set
; x = SetIf(a). The setcc instruction works with a flag as an input.

%macro Set.mu64 2
  mov al, byte [rdi + %2]
  cmp al, 0
  setne al
  movzx rax, al
  mov qword [rdi + %1], rax
%endmacro

%macro Set.ms64 2
  mov al, byte [rdi + %2]
  cmp al, 0
  setne al
  movzx rax, al
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Movzx
; x = a. x and a must be the same unsigned number types.

;%macro Movzx.mu8 2
;  mov al, byte [rdi + %2]
;  movzx ax, al
;  mov word [rdi + %1], ax
;%endmacro

;%macro Movzx.mu16 2
;  mov ax, word [rdi + %2]
;  movzx eax, ax
;  mov dword [rdi + %1], eax
;%endmacro

;%macro Movzx.mu32 2
;  mov eax, dword [rdi + %2]
;  movzx rax, eax
;  mov qword [rdi + %1], rax
;%endmacro

; -----------------------------------------------------------------------------
; Conversion instructions
; x = (AtoB)a. a must be of type A, x must be of type B.

; v0.1

%macro s8tos16.m 2
  mov al, byte [rdi + %2]
  movsx ax, al
  mov word [rdi + %1], ax
%endmacro

%macro s8tos32.m 2
  mov al, byte [rdi + %2]
  movsx eax, al
  mov dword [rdi + %1], eax
%endmacro

%macro s8tos64.m 2
  mov al, byte [rdi + %2]
  movsx rax, al
  mov qword [rdi + %1], rax
%endmacro

%macro s16tos32.m 2
  mov ax, word [rdi + %2]
  movsx eax, ax
  mov dword [rdi + %1], eax
%endmacro

%macro s16tos64.m 2
  mov ax, word [rdi + %2]
  movsx eax, ax
  mov dword [rdi + %1], eax
%endmacro

%macro s32tos64.m 2
  mov eax, dword [rdi + %2]
  movsxd rax, eax
  mov qword [rdi + %1], rax
%endmacro

%macro u8tou16.m 2
  mov al, byte [rdi + %2]
  movzx ax, al
  mov word [rdi + %1], ax
%endmacro

%macro u8tou32.m 2
  mov al, byte [rdi + %2]
  movzx eax, al
  mov dword [rdi + %1], eax
%endmacro

%macro u8tou64.m 2
  mov al, byte [rdi + %2]
  movzx rax, al
  mov qword [rdi + %1], rax
%endmacro

%macro u16tou32.m 2
  mov ax, word [rdi + %2]
  movzx eax, ax
  mov dword [rdi + %1], eax
%endmacro

%macro u16tou64.m 2
  mov ax, word [rdi + %2]
  movzx rax, ax
  mov qword [rdi + %1], rax
%endmacro

; "mov rax, eax" zeroes out the upper part of rax
%macro u32tou64.m 2
  mov eax, dword [rdi + %2]
  mov rax, eax
  mov qword [rdi + %1], rax
%endmacro

;%macro s16tou8.m 2
;  mov ax, word [rdi + %2]
;  cmp ax, 255
;  cmovg ax, 255
;  cmp ax, 0
;  cmovl ax, 0
;  mov byte [rdi + %1], al
;%endmacro

%macro s16tos8.m 2
  ;pinsrw xmm0, word [rdi + %1], 0
  vpbroadcastw xmm0, word [rdi + %2]
  packsswb xmm0, xmm0
  pextrb byte [rdi + %1], xmm0, 0
%endmacro

%macro s32tos16.m 2
  ;pinsrd xmm0, dword [rdi + %1], 0
  vpbroadcastd xmm0, dword [rdi + %2]
  packssdw xmm0, xmm0
  pextrw word [rdi + %1], xmm0, 0
%endmacro

%macro u16tou8.m 2
  ;pinsrw xmm0, word [rdi + %1], 0
  vpbroadcastw xmm0, word [rdi + %2]
  packuswb xmm0, xmm0, xmm0
  pextrb byte [rdi + %1], xmm0, 0
%endmacro

%macro u32tou16.m 2
  ;pinsrd xmm0, dword [rdi + %1], 0
  vpbroadcastd xmm0, word [rdi + %2]
  packusdw xmm0, xmm0, xmm0
  pextrw word [rdi + %1], xmm0, 0
%endmacro

%macro u64tou32.m 2
  ;pinsrq xmm0, qword [rdi + %1], 0
  vpbroadcastq xmm0, qword [rdi + %2]
  vpmovusqd xmm0, xmm0
  pextrd dword [rdi + %1], xmm0, 0
%endmacro

%macro s64tos32.m 2
  ;pinsrq xmm0, qword [rdi + %1], 0
  vpbroadcastq xmm0, qword [rdi + %2]
  vpmovsqd xmm0, xmm0
  pextrd dword [rdi + %1], xmm0, 0
%endmacro

; Light polyfill

; Note: cmovl does not support moves to r8
%macro s8tou8.m 2
  mov al, byte [rdi + %2]
  cmp al, 0
  cmovl ax, 0
  mov byte [rdi + %1], al
%endmacro

%macro s16tou16.m 2
  mov ax, word [rdi + %2]
  cmp ax, 0
  cmovl ax, 0
  mov word [rdi + %1], ax
%endmacro

%macro s32tou32.m 2
  mov eax, dword [rdi + %2]
  cmp eax, 0
  cmovl eax, 0
  mov dword [rdi + %1], eax
%endmacro

%macro s64tou64.m 2
  mov rax, qword [rdi + %2]
  cmp rax, 0
  cmovl rax, 0
  mov qword [rdi + %1], rax
%endmacro

%macro u8tos8.m 2
  mov al, byte [rdi + %2]
  cmp al, 0x7F
  cmova ax, 0x7F
  mov byte [rdi + %1], al
%endmacro

%macro u16tos16.m 2
  mov ax, word [rdi + %2]
  cmp ax, 0x7FFF
  cmova ax, 0x7FFF
  mov word [rdi + %1], ax
%endmacro

%macro u32tos32.m 2
  mov eax, dword [rdi + %2]
  cmp eax, 0x7FFF_FFFF
  cmova eax, 0x7FFF_FFFF
  mov dword [rdi + %1], eax
%endmacro

; Note: Cmp does not support 64-bit immediate
%macro u64tos64.m 2
  mov rax, qword [rdi + %2]
  mov rcx, 0x7FFF_FFFF_FFFF_FFFF
  cmp rax, rcx
  cmova rax, rcx
  mov qword [rdi + %1], rax
%endmacro

%macro u8tos16.m 2
  mov al, byte [rdi + %2]
  movzx ax, al
  mov word [rdi + %1], ax
%endmacro

%macro u8tos32.m 2
  mov al, byte [rdi + %2]
  movzx eax, al
  mov dword [rdi + %1], eax
%endmacro

%macro u16tos32.m 2
  mov ax, word [rdi + %2]
  movzx eax, ax
  mov dword [rdi + %1], eax
%endmacro

%macro u32tos64.m 2
  mov eax, dword [rdi + %2]
  movzx rax, eax
  mov qword [rdi + %1], rax
%endmacro

%macro f32tof64.m 2
  movss xmm0, dword [rdi + %2]
  cvtss2sd xmm0, xmm0
  movsd [rdi + %1], xmm0
%endmacro

%macro f64tof32.m 2
  movsd xmm0, qword [rdi + %2]
  cvtsd2ss xmm0, xmm0
  movss dword [rdi + %1], xmm0
%endmacro

%macro f32tou32.m 2
  movss xmm0, [rdi + %2]
  cvttss2si eax, xmm0
  mov dword [rdi + %1], eax
%endmacro

%macro f32tos32.m 2
  movss xmm0, [rdi + %2]
  cvttss2si eax, xmm0
  mov dword [rdi + %1], eax
%endmacro

%macro f32tou64.m 2
  movss xmm0, [rdi + %2]
  cvttss2si rax, xmm0
  mov dword [rdi + %1], rax
%endmacro

%macro f32tos64.m 2
  movss xmm0, [rdi + %2]
  cvttss2si rax, xmm0
  mov qword [rdi + %1], rax
%endmacro

%macro f64tou64.m 2
  movsd xmm0, [rdi + %2]
  cvttsd2si rax, xmm0
  mov qword [rdi + %1], rax
%endmacro

%macro f64tos64.m 2
  movsd xmm0, [rdi + %2]
  cvttsd2si rax, xmm0
  mov qword [rdi + %1], rax
%endmacro

%macro s32tof32.m 2
  mov eax, dword [rdi + %2]
  cvtsi2ss xmm0, eax
  movsd [rdi + %1], xmm0
%endmacro

%macro s32tof64.m 2
  mov eax, dword [rdi + %2]
  cvtsi2sd xmm0, eax
  movsq [rdi + %1], xmm0
%endmacro

%macro s64tof32.m 2
  mov rax, qword [rdi + %2]
  cvtsi2ss xmm0, rax
  movsd [rdi + %1], xmm0
%endmacro

%macro s64tof64.m 2
  mov rax, qword [rdi + %2]
  cvtsi2sd xmm0, rax
  movsq [rdi + %1], xmm0
%endmacro

; Future


; -----------------------------------------------------------------------------
; Usigned integer to larger unsigned types
; u8tou16, u8tou32, u16tou32, u32tou64
; x = (AtoB)a. a must be of type A, x must be of type B.




; -----------------------------------------------------------------------------
; Usigned integer to larger signed types
; u8tos16, u16tos32, u32tos64
; x = (AtoB)a. a must be of type A, x must be of type B.




; -----------------------------------------------------------------------------
; Signed integer to larger signed types
; s8tos16, s16tos32, s32tos64
; x = (AtoB)a. a must be of type A, x must be of type B.



; -----------------------------------------------------------------------------


; -----------------------------------------------------------------------------
; Integer to floats
; u16tof32, s16tof32, u32tof64, s32tof64
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro u16tof32.m 2
  mov ax, word [rdi + %2]
  movzx eax, ax
  cvtsi2ss xmm0, eax
  movss [rdi + %1], xmm0
%endmacro

%macro s16tof32.m 2
  mov ax, word [rdi + %2]
  movsx eax, ax
  cvtsi2ss xmm0, eax
  movss [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Floats to larger types
; f32tof64
; x = (AtoB)a. a must be of type A, x must be of type B.



; -----------------------------------------------------------------------------
; Usigned integer to smaller unsigned types
; u16tou8, u32tou16, u64tou32
; x = (AtoB)a. a must be of type A, x must be of type B.



; -----------------------------------------------------------------------------
; Usigned integer to smaller unsigned types
; s16tou8, s32tou16, s64tou32
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro s16tou8.m 2
  mov ax, word [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro s32tou16.m 2
  mov eax, dword [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro s64tou32.m 2
  mov rax, qword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro


; -----------------------------------------------------------------------------
; Signed integer to smaller signed types
; s16tos8, s32tos16, s64tos32
; x = (AtoB)a. a must be of type A, x must be of type B.



; -----------------------------------------------------------------------------
; floats to integers
; f32tou16, f32tos16, f64tou32, f64tos32
; x = (AtoB)a. a must be of type A, x must be of type B.



; -----------------------------------------------------------------------------
; Floats to smaller floats
; f64tof32
; x = (AtoB)a. a must be of type A, x must be of type B.

; -----------------------------------------------------------------------------
; Packed integers to larger types
; u8x8tou16x8, u8x4tou32x4, u8x2tou64x2, u16x4tou32x4, u32x2tou64x2
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro u8x8tou16x8.m 2
  mov rax, qword [rdi + %2]
  movq xmm0, rax
  pmovzxbw xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro u8x4tou32x4.m 2
  mov rax, 0
  mov eax, dword [rdi + %2]
  movq xmm0, rax
  pmovzxbd xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro u8x2tou64x2.m 2
  mov rax, 0
  mov ax, word [rdi + %2]
  movq xmm0, rax
  pmovzxdq xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro u16x4tou32x4.m 2
  movq xmm0, qword [rdi + %2]
  pmovzxwd xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro u32x2tou64x2.m 2
  movq xmm0, qword [rdi + %2]
  pmovzxdq xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

; -----------------------------------------------------------------------------
; Packed signed integers to larger types
; s8x8tos16x8, s8x4tos32x4
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro s8x8tos16x8.m 2
  movq xmm0, qword [rdi + %2]
  pmovsxbw xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro s8x4tos32x4.m 2
  mov rax, 0
  mov eax, dword [rdi + %2]
  movq xmm0, rax
  pmovsxbd xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

; -----------------------------------------------------------------------------
; Packed integers to smaller types
; s64x2tos32x2
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro s64x2tos32x2.m 2
  movq xmm0, qword [rdi + %2]
  vpmovqd xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

; -----------------------------------------------------------------------------
; Packed floats to smaller types
; f64x2tof32x2, f32x4tof16x2
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro f64x2tof32x2.m 2
  movdqu xmm0, oword [rdi + %2]
  cvtpd2ps xmm1, xmm0
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro f32x4tof16x4.m 2
  movdqu xmm0, oword [rdi + %2]
  vcvtps2ph xmm1, xmm0, 0
  movdqu oword [rdi + %1], xmm1
%endmacro

; -----------------------------------------------------------------------------
; Two packed floats downconverted and combined
; f64x4tof32x4, f32x8tof16x8
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro f64x4tof32x4.mm 3
  movdqu xmm0, oword [rdi + %2]
  cvtpd2ps xmm0, xmm0
  movdqu xmm1, oword [rdi + %3]
  cvtpd2ps xmm1, xmm1
  pslldq xmm1, 8
  vpor xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro f32x8tof16x8.mm 3
  movdqu xmm0, oword [rdi + %2]
  vcvtps2ph xmm0, xmm0, 0
  movdqu xmm1, oword [rdi + %3]
  vcvtps2ph xmm1, xmm1, 0
  pslldq xmm1, 8
  vpor xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Packed floating point numbers up-converted and stored in two vars
; f32x4tof64x4
; x = (AtoB)a. a must be of type A, x must be of type B.

; TODO: Can we use vinsertf128?
%macro f32x4tof64x4.mm 3
  movdqu xmm0, oword [rdi + %3]
  movdqu xmm1, xmm0
  cvtps2pd xmm1, xmm1
  movdqu xmm2, xmm0
  psrldq xmm2, 8
  cvtps2pd xmm2, xmm2
  movdqu oword [rdi + %1], xmm1
  movdqu oword [rdi + %2], xmm2
%endmacro

; -----------------------------------------------------------------------------
; Packed ints to smaller types
; u64x2tou32x2, u32x4tou16x2
; x = (AtoB)a. a must be of type A, x must be of type B.

; TODO: Find correct instructions
;%macro f64x2tof32x2.m 2
  ;movdqu xmm0, oword [rdi + %2]
  ;packusdw xmm1, xmm0
  ;movdqu oword [rdi + %1], xmm1
;%endmacro

; -----------------------------------------------------------------------------
; Reinterpret as a different type
; x = (B)a. x must be target type. a must be one of the supported types.

; v0.1

%macro Xb8.mu8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Xu8.mb8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Xb8.ms8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro

%macro Xs8.mb8 2
  mov al, byte [rdi + %2]
  mov byte [rdi + %1], al
%endmacro


%macro Xb16.mu16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Xu16.mb16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Xb16.ms16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro

%macro Xs16.mb16 2
  mov ax, word [rdi + %2]
  mov word [rdi + %1], ax
%endmacro


%macro Xb32.mu32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xu32.mb32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xu32.mm32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xb32.ms32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xs32.mb32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xb32.mf32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro

%macro Xf32.mb32 2
  mov eax, dword [rdi + %2]
  mov dword [rdi + %1], eax
%endmacro


%macro Xu64.mb64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xb64.mu64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xs64.mb64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xb64.ms64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xf64.mb64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xb64.mf64 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro


%macro Xu8x16.mb8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xb8x16.mu8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xs8x16.mb8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xb8x16.ms8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xb8x16.mb16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xu8x16a.mu16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xb16x8.mu16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xu8x16.mb16x8 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro


; Future


; Between array types
%macro Xu8a.mu16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xu16a.mu32a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xu64a.mu64x2a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro


; Between bit-array types

%macro Xb128.mu8x16 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Xb256.mu8x32 2
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu yword [rdi + %1], ymm0
%endmacro



; SIMD-types
%macro Xu32x4.mb32x4 2
  movdqu xmm0, oword [rdi + %2]
  movdqu oword [rdi + %1], xmm0
%endmacro


; SIMD array types
%macro Xu16x8a.mu16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro


%macro Xu16x16a.mb16x16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xb8x32.mb16x16 2
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu yword [rdi + %1], ymm0
%endmacro

%macro Xb8x64.mb16x32 2
  vmovdqu16 zmm0, zword [rdi + %2]
  vmovdqu8 zword [rdi + %1], zmm0
%endmacro

%macro Xu16x16a.mu16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

%macro Xu16x32a.mu16a 2
  mov rax, qword [rdi + %2]
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Signed integer to smaller signed type with saturation
; u32tou16s
; x = (AtoB)a. a must be of type A, x must be of type B.

%macro u32tou16s.m 2
  mov rax, 0
  mov eax, dword [rdi + %2]
  movq xmm0, rax
  packusdw xmm0, xmm0
  movq rax, xmm0
  mov word [rdi + %1], ax
%endmacro

%macro s32tos16s.m 2
  mov rax, 0
  mov eax, dword [rdi + %2]
  movq xmm0, rax
  packssdw xmm0, xmm0
  movq rax, xmm0
  mov word [rdi + %1], ax
%endmacro


; -----------------------------------------------------------------------------
; Ror
; x = a op b. x, a must be bitfield types. b must be a number.

%macro Ror.mib32 3
  mov eax, dword [rdi + %2]
  ror eax, %3
  mov dword [rdi + %1], eax
%endmacro

%macro Ror.mib64 3
  mov rax, qword [rdi + %2]
  ror rax, %3
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Rol
; x = a op b. x, a must be bitfield types. b must be a number.

%macro Rol.mib32 3
  mov eax, dword [rdi + %2]
  rol eax, %3
  mov dword [rdi + %1], rax
%endmacro

%macro Rol.mib64 3
  mov rax, qword [rdi + %2]
  rol rax, %3
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; IsZero
; x = a = 0. x can be bit or number. a must be a boolean.

%macro IsZero.mb32 2
  mov eax, dword [rdi + %2]
  test eax, eax
  setz al
  mov byte [rdi + %1], al
%endmacro

; -----------------------------------------------------------------------------
; IsNonZero
; x = a != 0. x can be bit or number. a must be a boolean.

%macro IsNonZero.mb32 2
  mov eax, dword [rdi + %2]
  test eax, eax
  setnz al
  mov byte [rdi + %1], al
%endmacro

; -----------------------------------------------------------------------------
; Cmov
; x = a ? b : x. x, b must be the same types. a must be a boolean.

%macro Cmov.mms64 3
  mov rdx, qword [rdi + %2]
  mov al, byte [rdi + %3]
  test al, al
  cmovnz rax, rdx
  mov qword [rdi + %1], rax
%endmacro

; Cmovcc
; x = (a op b) ? b : x. x, b must be the same types. a and b must be the same types or number types.
; op can be 'a', 'ae', 'b', 'be', 'c', 'e', 'g', 'ge', 'l', 'le', 'na', 'nae', 'nb', 'nbe', 'nc', 'ne', 'ng', 'nge', 'nl', 'nle', 'no', 'np', 'ns', 'nz', 'o', 'p', 'pe', 'po', 's', 'z'
; Comparizons: 'e', 'ne', 'g', 'ge', 'l', 'le'
; Arithmetic: 'z', 'o', 's', 'p'

%macro Cmoveq.mms64 4
  mov rax, qword [rdi + %3]
  mov rdx, qword [rdi + %4]
  mov rcx, qword [rdi + %2]
  cmp rax, rdx
  cmovz rax, rcx
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Xchg
; a op b. a and b must be the same types.

%macro Xchg.ms64 2
  mov rax, qword [rdi + %2]
  xchg rax, qword [rdi + %1]
  mov qword [rdi + %2], rax
%endmacro

; -----------------------------------------------------------------------------
; Xadd
; In one go: a' = a + b; b' = a

%macro Xadd.ms64 2
  mov rax, qword [rdi + %2]
  xadd qword [rdi + %1], rax
  mov qword [rdi + %2], rax
%endmacro

; -----------------------------------------------------------------------------
; Bswap
; x = bswap(a). a and x must be bitfields.

%macro Bswap.mb64 2
  mov rax, qword [rdi + %2]
  bswap rax
  mov qword [rdi + %1], rax
%endmacro

%macro Bswap.mb32 2
  mov eax, dword [rdi + %2]
  bswap eax
  mov dword [rdi + %1], eax
%endmacro

%macro Bswap.mb16 2
  mov ax, word [rdi + %2]
  xchg ah, al
  mov word [rdi + %1], ax
%endmacro

; -----------------------------------------------------------------------------
; Bsf -- Bit scan forward, find first set bit rightwards
; x = Bsf(a). a must be a bitfield. x is a number.

%macro Bsf.mb64 2
  mov rax, qword [rdi + %2]
  bsf rax, rax
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Bsr -- Bit scan reverse, find first set bit leftwards
; x = Bsr(a). a must be a bitfield. x is a number.

%macro Bsr.mb64 2
  mov rax, qword [rdi + %2]
  bsr rax, rax
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Bt -- Bit test
; x = Bt(a). a must be a bitfield. x is a boolean.

%macro Bt.miu64 3
  mov rax, qword [rdi + %2]
  bt rax, %3
  setc al
  movzx rax, al
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; CmpXchg -- Compare and Exchange
; x = (a == b) ? (b = c, 1) : (a = b, 0)

%macro CmpXchg.mms64 4
  mov rax, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  mov rdx, qword [rdi + %4]
  cmpxchg rcx, rdx
  setz r8b
  mov byte [rdi + %1], r8b
  mov qword [rdi + %2], rax
  mov qword [rdi + %3], rcx
%endmacro

; -----------------------------------------------------------------------------
; Crc32 -- Cyclic redundancy check
; x = crc32(a)

%macro Crc32.mu32 2
  mov eax, dword [rdi + %1]
  mov ecx, dword [rdi + %2]
  crc32 eax, ecx
  mov dword [rdi + %1], eax
%endmacro

; -----------------------------------------------------------------------------
; Movs -- Move String, Block copy
; x = Movs(a, len). a and x must be arrays, len must be a number.

%macro Movs.mmu8a 3
  cld
  mov rsi, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  mov rbx, rdi
  mov rdi, qword [rdi + %1]
  rep movsb
  mov rdi, rbx
%endmacro

%macro Movs.mmu16a 3
  cld
  mov rsi, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  mov rbx, rdi
  mov rdi, qword [rdi + %1]
  rep movsw
  mov rdi, rbx
%endmacro

%macro Movs.mmu32a 3
  cld
  mov rsi, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  mov rbx, rdi
  mov rdi, qword [rdi + %1]
  rep movsd
  mov rdi, rbx
%endmacro

%macro Movs.mmu64a 3
  cld
  mov rsi, qword [rdi + %2]
  mov rcx, qword [rdi + %3]
  mov rbx, rdi
  mov rdi, qword [rdi + %1]
  rep movsq
  mov rdi, rbx
%endmacro

; -----------------------------------------------------------------------------
; Cmps -- Compare strings
; x = Cmps(a, b, len). a, b must be arrays, len must be a number, x must be a boolean.

%macro Cmps.mmu8a 4
  cld
  mov rsi, qword [rdi + %3]
  mov rcx, qword [rdi + %4]
  mov rbx, rdi
  mov rdi, qword [rdi + %2]
  rep cmpsb
  mov rdi, rbx
  setz byte [rdi + %1]
%endmacro

%macro Cmps.mmu16a 4
  cld
  mov rsi, qword [rdi + %3]
  mov rcx, qword [rdi + %4]
  mov rbx, rdi
  mov rdi, qword [rdi + %2]
  rep cmpsw
  mov rdi, rbx
  setz byte [rdi + %1]
%endmacro

%macro Cmps.mmu32a 4
  cld
  mov rsi, qword [rdi + %3]
  mov rcx, qword [rdi + %4]
  mov rbx, rdi
  mov rdi, qword [rdi + %2]
  rep cmpsd
  mov rdi, rbx
  setz byte [rdi + %1]
%endmacro

%macro Cmps.mmu64a 4
  cld
  mov rsi, qword [rdi + %3]
  mov rcx, qword [rdi + %4]
  mov rbx, rdi
  mov rdi, qword [rdi + %2]
  rep cmpsq
  mov rdi, rbx
  setz byte [rdi + %1]
%endmacro

; -----------------------------------------------------------------------------
; Scas -- Block scan, find index of byte %3 in array %2
; x = Scas(a, c, len). a must be an array, c a character, len must be a number, x must be a number.

%macro Scas.mmu8a 4
  cld
  mov al, byte [rdi + %3]
  mov rcx, qword [rdi + %4]
  mov rbx, rdi
  mov rdi, qword [rdi + %2]
  repne scasb
  sete r8b
  movzx r8, r8b
  mov rdi, rbx
  sub rcx, qword [rdi + %4]
  neg rcx
  sub rcx, r8
  mov qword [rdi + %1], rcx
%endmacro

; -----------------------------------------------------------------------------
; Popcnt -- Population count -- count ones set
; x = Popcnt(a). a is a bitfield, x a number.

%macro Popcnt.mb64 2
  mov rax, qword [rdi + %2]
  popcnt rax, rax
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Lzcnt -- Leading zero count
; x = Lzcnt(a). a is a bitfield, x a number.

%macro Lzcnt.mu64b64 2
  mov rax, qword [rdi + %2]
  lzcnt rax, rax
  mov qword [rdi + %1], rax
%endmacro

%macro Lzcnt.mu64b32 2
  mov rax, 0
  mov eax, dword [rdi + %2]
  lzcnt rax, rax
  sub rax, 32
  mov qword [rdi + %1], rax
%endmacro

%macro Lzcnt.mu64b16 2
  mov rax, 0
  mov ax, word [rdi + %2]
  lzcnt rax, rax
  sub rax, 48
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Tzcnt -- Trailing zero count
; x = Tzcnt(a). a is a bitfield, x a number.

%macro Tzcnt.mb64 2
  mov rax, qword [rdi + %2]
  tzcnt rax, rax
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Rdtsc -- Read time stamp counter
; x = Rdtsc(). x is a number.

%macro Rdtsc.mu64 1
  rdtsc
  shl rdx, 32
  or rax, rdx
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Rdpmc -- Read performance counter
; x = Rdpmc(a). x, a is a number.

%macro Rdpmc.mu64 2
  mov rcx, qword [rdi + %2]
  rdpmc
  shl rdx, 32
  or rax, rdx
  mov qword [rdi + %1], rax
%endmacro

; -----------------------------------------------------------------------------
; Nop -- No operation
; No parameters

%macro Nop 0
  nop
%endmacro

; -----------------------------------------------------------------------------
; Bextr -- Bitfield extract -- dest = bits a length b from src
; x = Bextr(a, b, c). x, a are bitfields. b and c are numbers.

%macro Bextr.mmb64 4
  mov rax, 0
  mov al, byte [rdi + %3]
  mov ah, byte [rdi + %4]
  mov rcx, qword [rdi + %2]
  bextr rdx, rcx, rax
  mov qword [rdi + %1], rdx
%endmacro

; -----------------------------------------------------------------------------
; Blsi -- Extract Lowest Set Isolated Bit
; x = Blsi(a). a are bitfields. x is a number.

%macro Blsi.mb64 2
  mov rax, qword [rdi + %2]
  blsi rdx, rax
  mov qword [rdi + %1], rdx
%endmacro

; -----------------------------------------------------------------------------
; Blsmsk -- Generate bitmask
; x = Blsmsk(a). x, a are bitfields.

%macro Blsmsk.mb64 2
  mov rax, qword [rdi + %2]
  blsmsk rdx, rax
  mov qword [rdi + %1], rdx
%endmacro

; -----------------------------------------------------------------------------
; Blsr -- Clear lowest bit set
; x = Blsr(a). x, a are bitfields.

%macro Blsr.mb64 2
  mov rax, qword [rdi + %2]
  blsr rdx, rax
  mov qword [rdi + %1], rdx
%endmacro

; -----------------------------------------------------------------------------
; Bzhi -- Clear high order bits
; x = Bzhi(a). x, a are bitfields.

%macro Bzhi.mmb64 3
  mov rax, 0
  mov al, byte [rdi + %3]
  mov rdx, qword [rdi + %2]
  bzhi rcx, rdx, rax
  mov qword [rdi + %1], rcx
%endmacro

; -----------------------------------------------------------------------------
; Pdep -- Parallel bit deposit
; x = Pdep(a, b). x, a, b are bitfields.

%macro Pdep.mmb64 3
  mov rdx, qword [rdi + %2]
  mov rax, qword [rdi + %3]
  pdep rcx, rdx, rax
  mov qword [rdi + %1], rcx
%endmacro

; -----------------------------------------------------------------------------
; Pext -- Parallel bit extract
; x = Pext(a, b). x, a, b are bitfields.

%macro Pext.mmb64 3
  mov rdx, qword [rdi + %2]
  mov rax, qword [rdi + %3]
  pext rcx, rdx, rax
  mov qword [rdi + %1], rcx
%endmacro

; -----------------------------------------------------------------------------
; ExtractMask -- Extract Byte Mask
; x = ExtractMask(a). a is an 8xX-bit, x is X-bit

%macro ExtractMask.mb8x16 2
  movdqu xmm1, oword [rdi + %2]
  pmovmskb eax, xmm1
  mov word [rdi + %1], ax
%endmacro

%macro ExtractMask.mb8x32 2
  vmovdqu ymm0, yword [rdi + %2]
  vpmovmskb rax, ymm0
  mov dword [rdi + %1], eax
%endmacro

;%macro ExtractMask.mu16x8 2
;  movdqu xmm1, oword [rdi + %2]
;  pmovmskb eax, xmm1
;  mov dword [rdi + %1], eax
;%endmacro

%macro ExtractMask.mb8x64 2
  vmovdqu8 zmm0, zword [rdi + %2]
  vpmovb2m k1, zmm0
  kmovq qword [rdi + %1], k1
%endmacro


; -----------------------------------------------------------------------------
; Shuffle -- Shuffle data
; x = Shuffle(a, b). a, b, x are the same packed number type.

%macro Shuffle.mmu8x16 3
  movdqu xmm0, oword [rdi + %1]
  movdqu xmm1, oword [rdi + %2]
  movdqu xmm2, oword [rdi + %3]
  vpshufb xmm0, xmm1, xmm2
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Shuffle.miu32x4 6
  movdqu xmm0, oword [rdi + %1]
  movdqu xmm1, oword [rdi + %2]
  vpshufd xmm0, xmm1, (%3<<6)|(%4<<4)|(%5<<2)|(%6<<0)
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; MulStoreHigh -- Multiply Store high
; x = MulStoreHigh(a, b). a, b, x are the same number type.

%macro MulStoreHigh.mmu16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  vpmulhuw xmm0, xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro MulStoreHigh.mmu16x16 3
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vpmulhuw ymm0, ymm0, ymm1
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; SelectiveCopy -- Conditionally copy from one SIMD register to another
; x = SelectiveCopy(a, b, c). a, b, c, x are the same packed number types.

%macro SelectiveCopy.mmu8x16 4
  movdqu xmm1, oword [rdi + %2]
  movdqu xmm2, oword [rdi + %3]
  movdqu xmm0, oword [rdi + %4]
  pblendvb xmm1, xmm2
  movdqu oword [rdi + %1], xmm1
%endmacro

%macro SelectiveCopy.mmu8x32 4
  vmovdqu ymm0, yword [rdi + %2]
  vmovdqu ymm1, yword [rdi + %3]
  vmovdqu ymm2, yword [rdi + %4]
  vpblendvb ymm0, ymm0, ymm1, ymm2
  vmovdqu yword [rdi + %1], ymm0
%endmacro

; -----------------------------------------------------------------------------
; MultiplyAndAdd -- Fused Multiply and add
; x = MultiplyAndAdd(a, b, c). a, b, c, x are the same packed number types.

%macro MultiplyAndAdd.mmf32x4 4
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  movdqu xmm2, oword [rdi + %4]
  vfmadd123ps xmm0, xmm1, xmm2
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Avg -- Average of two numbers
; x = Avg(a, b). a, b, x are the same number types.

%macro Avg.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pavgb xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Min -- Minimum of two numbers
; x = Min(a, b). a, b, x are the same number types.

; v0.1

%macro Min.mmb1u8 2
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  cmova ax, dx
  mov byte [rdi + %2], al
%endmacro

%macro Min.mmb1u16 2
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  cmova ax, dx
  mov word [rdi + %2], ax
%endmacro

%macro Min.mmb1u32 2
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  cmova eax, edx
  mov dword [rdi + %2], eax
%endmacro

%macro Min.mmb1u64 2
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  cmova rax, rdx
  mov qword [rdi + %2], rax
%endmacro

%macro Min.mmb1s8 2
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  cmova ax, dx
  mov byte [rdi + %2], al
%endmacro

%macro Min.mmb1s16 2
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  cmova ax, dx
  mov word [rdi + %2], ax
%endmacro

%macro Min.mmb1s32 2
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  cmova eax, edx
  mov dword [rdi + %2], eax
%endmacro

%macro Min.mmb1s64 2
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  cmova rax, rdx
  mov qword [rdi + %2], rax
%endmacro

%macro Min.mmf32 3
  movd xmm0, dword [rdi + %2]
  movd xmm1, dword [rdi + %3]
  minss xmm0, xmm1
  movd dword [rdi + %1], xmm0
%endmacro

%macro Min.mmf64 3
  movq xmm0, qword [rdi + %2]
  movq xmm1, qword [rdi + %3]
  minsd xmm0, xmm1
  movq qword [rdi + %1], xmm0
%endmacro

%macro Min.mmb16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pminuw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Min.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pminsw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Min.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pminub xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Max -- Maximum of two numbers
; x = Max(a, b). a, b, x are the same number types.

; v0.1

%macro Max.mmb1u8 2
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  cmovb ax, dx
  mov byte [rdi + %2], al
%endmacro

%macro Max.mmb1u16 2
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  cmovb ax, dx
  mov word [rdi + %2], ax
%endmacro

%macro Max.mmb1u32 2
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  cmovb eax, edx
  mov dword [rdi + %2], eax
%endmacro

%macro Max.mmb1u64 2
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  cmovb rax, rdx
  mov qword [rdi + %2], rax
%endmacro

%macro Max.mmb1s8 2
  mov al, byte [rdi + %2]
  mov dl, byte [rdi + %3]
  cmp al, dl
  cmovb ax, dx
  mov byte [rdi + %2], al
%endmacro

%macro Max.mmb1s16 2
  mov ax, word [rdi + %2]
  mov dx, word [rdi + %3]
  cmp ax, dx
  cmovb ax, dx
  mov word [rdi + %2], ax
%endmacro

%macro Max.mmb1s32 2
  mov eax, dword [rdi + %2]
  mov edx, dword [rdi + %3]
  cmp eax, edx
  cmovb eax, edx
  mov dword [rdi + %2], eax
%endmacro

%macro Max.mmb1s64 2
  mov rax, qword [rdi + %2]
  mov rdx, qword [rdi + %3]
  cmp rax, rdx
  cmovb rax, rdx
  mov qword [rdi + %2], rax
%endmacro

%macro Max.mmf32 3
  movd xmm0, dword [rdi + %2]
  movd xmm1, dword [rdi + %3]
  maxss xmm0, xmm1
  movd dword [rdi + %1], xmm0
%endmacro

%macro Max.mmf64 3
  movq xmm0, qword [rdi + %2]
  movq xmm1, qword [rdi + %3]
  maxsd xmm0, xmm1
  movq qword [rdi + %1], xmm0
%endmacro

%macro Max.mmb16x8u16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmaxuw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro Max.mmb16x8s16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmaxsw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro




; Future

%macro Max.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmaxub xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Sqrt -- Square root
; x = Sqrt(a). a, x are the same number types.

; v0.1

%macro Sqrt.mf32 2
  movd xmm0, dword [rdi + %2]
  sqrtss xmm0, xmm0
  movd dword [rdi + %1], xmm0
%endmacro

%macro Sqrt.mf64 2
  movq xmm0, qword [rdi + %2]
  sqrtsd xmm0, xmm0
  movq qword [rdi + %1], xmm0
%endmacro




; Future


%macro Sqrt.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  sqrtps xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; ApproxReciprocal -- x = approx(1 / a)
; x = ApproxReciprocal(a). a, x are the same number types.

%macro ApproxReciprocal.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  rcpps xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; ApproxReciprocalSqrt -- x = approx(1 / sqrt(a))
; x = ApproxReciprocalSqrt(a). a, x are the same number types.

%macro ApproxReciprocalSqrt.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  rsqrtps xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; InterleaveLow -- Interleaves pairs from low data from both vectors
; x = InterleaveLow(a, b). a, b, x are the same packed number types.

%macro InterleaveLow.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  punpckldq xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; InterleaveHigh -- Interleaves pairs from high data from both vectors
; x = InterleaveLow(a, b). a, b, x are the same packed number types.

%macro InterleaveHigh.mmu32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  punpckhdq xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; CombineExtract -- Combine and extract a part offset by a constant
; x = CombineExtract(a, b. c). a, b are bitfields, c is a number.

%macro CombineExtract.mmiu8x16 4
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  palignr xmm0, xmm1, %4
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; Gather -- Gather data into array
; x = CombineExtract(p, a, b). p is a pointer. x, a and b are packed number types.

%macro Gather.mmmu32x4 4
  mov rax, qword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  movdqu xmm2, oword [rdi + %4]
  vpgatherdd xmm0, [rax + xmm1 * 4], xmm2
  movdqu oword [rdi + %1], xmm0
%endmacro


; -----------------------------------------------------------------------------
; SumAbsoluteDifference -- Sum of absolute differences
; x = SumAbsoluteDifference(a, b). a, b, x are packed number types.

%macro SumAbsoluteDifference.mmu8x16 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  psadbw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; PairwiseAdd -- Pairwiser horizontal add
; x = PairwiseAdd(a, b). a, b, x are packed number types.

%macro PairwiseAdd.mms16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  phaddw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; PairwiseSub -- Pairwiser horizontal subtract
; x = PairwiseSub(a, b). a, b, x are packed number types.

%macro PairwiseSub.mms16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  phsubw xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; PairwiseMulAdd -- Multiply vertical pairs and add horizontally
; x = PairwiseMulAdd(a, b). a, b, x are packed number types.

%macro PairwiseMulAdd.mms16x8 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  pmaddwd xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; AlternatingSubAdd -- Alternating subtract and add
; x = AlternatingSubAdd(a, b). a, b, x are packed number types.

%macro AlternatingSubAdd.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  addsubps xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; ConditionalNegate -- Conditionally nagate
; x = ConditionalNegate(a, b). a, b, x are packed number types.

%macro ConditionalNegate.mms32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  psignd xmm0, xmm1
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; DotProduct -- Dot Product
; x = a ⋅ b -- All parameters are the same multiple type.

%macro DotProduct.mmf32x4 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  dpps xmm0, xmm1, 0b1111_1111
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro DotProduct.mmf64x2 3
  movdqu xmm0, oword [rdi + %2]
  movdqu xmm1, oword [rdi + %3]
  dppd xmm0, xmm1, 0b0011_0011
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; StringSubset -- Identify the occurance of characters in a string
; x = StringSubset(a, b, l). x, a, b are packed bytes. l is a number.

%macro StringSubset.mmmiu8x16 5
  movdqu xmm1, oword [rdi + %3]
  mov rax, qword [rdi + %4]
  movdqu xmm2, oword [rdi + %2]
  mov rdx, %5
  pcmpestrm xmm1, xmm2, (0 << 6) + (0 << 2)
  vpextrw eax, xmm0, 0
  mov word [rdi + %1], ax
%endmacro

;%macro StringSubset.mmmiu16x8 5
;  movdqu xmm1, oword [rdi + %3]
;  mov rax, qword [rdi + %4]
;  movdqu xmm2, oword [rdi + %2]
;  mov rdx, %5
;  pcmpestrm xmm1, xmm2, (0 << 6) + (0 << 2)
;  vpextrw eax, xmm0, 0
;  mov word [rdi + %1], ax
;%endmacro

; -----------------------------------------------------------------------------
; StringRangeCheck -- Find members of a range
; x = StringRangeCheck(a, b, l). x, a, b are packed bytes. l is a number.

%macro StringRangeCheck.mmmiu8x16 5
  movdqu xmm1, oword [rdi + %3]
  mov rax, qword [rdi + %4]
  movdqu xmm2, oword [rdi + %2]
  mov rdx, %5
  pcmpestrm xmm1, xmm2, (0 << 6) + (1 << 2)
  vpextrw eax, xmm0, 0
  mov word [rdi + %1], ax
%endmacro

; -----------------------------------------------------------------------------
; MatchString -- Match string
; x = MatchString(a, b, l). x, a, b are packed bytes. l is a number.

%macro MatchString.mmmiu8x16 4
  movdqu xmm1, oword [rdi + %3]
  mov rax, qword [rdi + %4]
  movdqu xmm2, oword [rdi + %2]
  mov rdx, %5
  pcmpestrm xmm1, xmm2, (0 << 6) + (2 << 2)
  vpextrw eax, xmm0, 0
  mov word [rdi + %1], ax
%endmacro

; -----------------------------------------------------------------------------
; FindSubstring -- Locate string
; x = FindSubstring(a, al, b, bl). x, a, b are packed bytes. al, bl are a numbers.

%macro FindSubstring.mmmmu64 5
  movdqu xmm1, oword [rdi + %4]
  mov rax, qword [rdi + %5]
  movdqu xmm2, oword [rdi + %2]
  mov rdx, qword [rdi + %3]
  pcmpestrm xmm1, xmm2, (0 << 6) + (3 << 2)
  vpextrw eax, xmm0, 0
  mov word [rdi + %1], ax
%endmacro

%macro FindSubstring.mimiu64 5
  movdqu xmm1, oword [rdi + %4]
  mov rax, %5
  movdqu xmm2, oword [rdi + %2]
  mov rdx, %3
  pcmpestrm xmm1, xmm2, (0 << 6) + (3 << 2)
  vpextrw eax, xmm0, 0
  mov word [rdi + %1], ax
%endmacro

; -----------------------------------------------------------------------------
; MovAndDuplicate -- Copy data and duplicate even columns
; x = MovAndDuplicate(a). x and a are packed number types.

%macro MovAndDuplicate.mf64x2 2
  movdqu xmm0, oword [rdi + %2]
  movddup xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

%macro MovAndDuplicate.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  movsldup xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro

; -----------------------------------------------------------------------------
; MovAndDuplicateOdd -- Copy data and duplicate odd columns
; x = MovAndDuplicate(a). x and a are packed number types.

%macro MovAndDuplicateOdd.mf32x4 2
  movdqu xmm0, oword [rdi + %2]
  movshdup xmm0, xmm0
  movdqu oword [rdi + %1], xmm0
%endmacro















